### PR TITLE
Optimize image size

### PR DESCRIPTION
**Pull request by Eddi2015**

### CODE REVIEW

**Comment by Eddi2015** [comment]
What is this CLAassistent thing? Seems scary to me.

**Comment by fionera** [comment]
A Contributor License Agreement (CLA) defines the terms under which intellectual property has been contributed to a company/project, typically software under an open source license.

**Comment by fionera** [comment]
Its only that when you contribute, you accept that the intellectual property is handed to use. So that smth like the Bukkit DMCA cannot happen

**Comment by Eddi2015** [comment]
Well I think this PR is not worth it.

**Pull request closed without merging**
